# Generated by Django 3.1.4 on 2021-01-17 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Название курса')),
                ('anons', models.TextField(default='', max_length=1000, verbose_name='Анонс курса')),
                ('description', models.TextField(default='', max_length=1000000, verbose_name='Описание курса')),
                ('course_avatar', models.ImageField(default='images/courses/py.png', upload_to='images/courses/', verbose_name='Аватар курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Homeworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок сдачи')),
                ('date_of_beggining', models.DateTimeField(default=datetime.datetime(2021, 1, 17, 23, 5, 9, 945556), verbose_name='Дата начала выполнения')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Название домашнего задания')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Описание домашнего задания')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-date_of_beggining'],
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Название материала')),
                ('description', models.TextField(default='', max_length=250, verbose_name='Описание материала')),
                ('material_сontent', models.TextField(default='', max_length=1000000, verbose_name='Материал')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Материалы курса',
                'verbose_name_plural': 'Материалы курсов',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentsHomeworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.TextField(default='', verbose_name='Материал домашней работы')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
            ],
            options={
                'verbose_name': 'Домашнее задание студента',
                'verbose_name_plural': 'Домашние задания студентов',
            },
        ),
    ]
