# Generated by Django 3.1.4 on 2021-01-17 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentshomeworks',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='studentshomeworks',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='courses.homeworks', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='materials',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', related_query_name='course', to='courses.courses', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='homeworks',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='courses.courses', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='courses',
            name='confidants',
            field=models.ManyToManyField(limit_choices_to={'is_staff': False}, related_name='confidants', to=settings.AUTH_USER_MODEL, verbose_name='Доверенные лица'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'is_staff': True}, related_name='teachers', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели курса'),
        ),
    ]
