# Generated by Django 3.1.4 on 2021-01-17 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210117_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworks',
            name='date_of_beggining',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 23, 7, 11, 480778), verbose_name='Дата начала выполнения'),
        ),
    ]
