# Generated by Django 3.1.4 on 2021-01-17 20:38

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20210117_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='confidants',
            field=models.ManyToManyField(limit_choices_to={'is_teacher': False}, related_name='confidants', to=settings.AUTH_USER_MODEL, verbose_name='Доверенные лица'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'is_teacher': True}, related_name='teachers', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели курса'),
        ),
        migrations.AlterField(
            model_name='homeworks',
            name='date_of_beggining',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 23, 38, 19, 434016), verbose_name='Дата начала выполнения'),
        ),
    ]
