# Generated by Django 3.1.4 on 2021-01-17 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин на сайте')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('begin_year', models.CharField(default='', max_length=10, verbose_name='Год поступления')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('degree', models.CharField(choices=[('Бакалавр', 'Бакалавр'), ('Специалист', 'Специалист'), ('Магистр', 'Магистр')], default='', max_length=50, verbose_name='Степень')),
                ('form', models.CharField(choices=[('Очная', 'Очная'), ('Заочная', 'Заочная'), ('Вечерняя', 'Вечерняя')], default='', max_length=50, verbose_name='Форма обучения')),
                ('pay', models.CharField(choices=[('Бюджетная', 'Бюджетная'), ('Контрактная', 'Контрактная')], default='', max_length=50, verbose_name='Основа обучения')),
                ('avatar', models.ImageField(default='images/profile/blank-avatar.jpg', upload_to='images/profile/', verbose_name='Аватар')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('vk_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на профиль VK')),
                ('fb_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на профиль Facebook')),
                ('linkedin_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на профиль LinkedIn')),
                ('instagram_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на профиль Instagram')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Флаг учителя')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
